# Generated by Django 5.1.5 on 2025-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolo',
            old_name='bolos',
            new_name='bolo',
        ),
        migrations.RenameField(
            model_name='bolo',
            old_name='receita',
            new_name='ingredientes',
        ),
    ]
