# Generated by Django 5.1.5 on 2025-01-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0002_rename_bolos_bolo_bolo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bolo',
        ),
    ]
