# Generated by Django 5.1.5 on 2025-01-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolo', '0003_delete_bolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criador', models.CharField(max_length=30)),
                ('bolo', models.CharField(max_length=30)),
                ('ingredientes', models.CharField(max_length=30)),
                ('preparo', models.CharField(max_length=30)),
                ('preco', models.SmallIntegerField(max_length=30)),
            ],
        ),
    ]
