# Generated by Django 5.1.5 on 2025-01-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolo',
            name='preco',
            field=models.SmallIntegerField(verbose_name=' R$'),
        ),
    ]
