# Generated by Django 5.1.5 on 2025-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0005_bolo_slug_alter_bolo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
    ]
