# Generated by Django 5.1.5 on 2025-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0006_alter_bolo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='immagem',
            field=models.URLField(default='https://sl.bing.net/jIgqWq3ske'),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='ingredientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='preparo',
            field=models.TextField(),
        ),
    ]
