# Generated by Django 5.1.5 on 2025-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0007_bolo_immagem_alter_bolo_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='calda',
            field=models.TextField(null=True),
        ),
    ]
