# Generated by Django 5.1.5 on 2025-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0008_bolo_calda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='immagem',
            field=models.URLField(default='https://cooknenjoy.com/wp-content/uploads/2020/06/bolo-abobora-02.jpg'),
        ),
    ]
