# Generated by Django 5.1.5 on 2025-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0009_alter_bolo_immagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='preparo_calda',
            field=models.TextField(null=True),
        ),
    ]
