# Generated by Django 5.1.5 on 2025-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0010_bolo_preparo_calda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='calda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bolo',
            name='preparo_calda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
