# Generated by Django 5.1.5 on 2025-01-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0011_alter_bolo_calda_alter_bolo_preparo_calda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_usuario', models.TextField(max_length=12)),
                ('email', models.EmailField(max_length=54)),
            ],
        ),
    ]
