# Generated by Django 5.1.5 on 2025-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0013_remove_usuario_nome_de_usuario_usuario_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(default='', max_length=22)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=22)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
