# Generated by Django 5.1.5 on 2025-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0014_cadastro_login_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_Bolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criador', models.CharField(max_length=30)),
                ('bolo', models.CharField(max_length=30)),
                ('ingredientes', models.TextField()),
                ('preparo', models.TextField()),
                ('preco', models.SmallIntegerField(verbose_name=' R$')),
                ('slug', models.SlugField(max_length=60)),
                ('imagem', models.ImageField(height_field=50, upload_to='', width_field=50)),
                ('calda', models.TextField(blank=True, null=True)),
                ('preparo_calda', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
