# Generated by Django 5.1.5 on 2025-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0015_form_bolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolo',
            name='immagem',
        ),
        migrations.AddField(
            model_name='bolo',
            name='imagem',
            field=models.ImageField(default='', height_field=50, upload_to='img', width_field=50),
        ),
        migrations.AlterField(
            model_name='form_bolo',
            name='imagem',
            field=models.ImageField(height_field=50, upload_to='img', width_field=50),
        ),
    ]
