# Generated by Django 5.1.5 on 2025-01-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0018_delete_image_remove_bolo_imagem_bolo_immagem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form_Bolo',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
