# Generated by Django 5.1.5 on 2025-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0019_delete_form_bolo_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolo',
            name='immagem',
        ),
        migrations.AddField(
            model_name='bolo',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
