# Generated by Django 5.1.5 on 2025-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0022_alter_bolo_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='criador',
            field=models.CharField(max_length=30),
        ),
    ]
