# Generated by Django 5.1.5 on 2025-02-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0028_bolo_data_publicada_alter_bolo_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='criador',
            field=models.CharField(max_length=50),
        ),
    ]
