# Generated by Django 5.1.5 on 2025-02-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0029_alter_bolo_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='data_publicada',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
