# Generated by Django 5.1.5 on 2025-02-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0030_alter_bolo_data_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolo',
            name='data_publicada',
        ),
    ]
