# Generated by Django 5.1.5 on 2025-02-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0032_bolo_data_publicada_alter_bolo_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolo',
            name='data_publicada',
        ),
    ]
