# Generated by Django 5.1.5 on 2025-02-03 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0039_alter_bolo_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='dataq',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 1, 37, 470292, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2025, 2, 3, 20, 1, 37, 470285, tzinfo=datetime.timezone.utc)),
        ),
    ]
