# Generated by Django 5.1.5 on 2025-02-03 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0040_bolo_dataq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='dataq',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 6, 48, 889701, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2025, 2, 3, 20, 6, 48, 889696, tzinfo=datetime.timezone.utc)),
        ),
    ]
