# Generated by Django 5.1.5 on 2025-02-03 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0041_alter_bolo_dataq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='dataq',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 8, 25, 781689, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2025, 2, 3, 20, 8, 25, 781678, tzinfo=datetime.timezone.utc)),
        ),
    ]
