# Generated by Django 5.1.5 on 2025-02-03 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0042_alter_bolo_dataq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='dataq',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
