# Generated by Django 5.1.5 on 2025-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolo', '0043_alter_bolo_dataq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='criador',
            field=models.CharField(default='', max_length=111),
        ),
    ]
